---

- hosts: all
  become: true
  tasks:

  - name: install updates (CentOS)
    tags: always
    ansible.builtin.dnf:
      update_only: yes
      update_cache: yes
    when: ansible_facts['distribution'] == "CentOS"

  - name: install updates (Ubuntu)
    tags: always 
    ansible.builtin.apt:
      upgrade: dist
      update_cache: yes
    when: ansible_facts['os_family'] == "Debian"


- hosts: web_servers
  become: true
  tasks:

  - name: install apache and php packages for Ubuntu servers
    tags: apache,apache2,ubuntu
    ansible.builtin.apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_facts['os_family'] == "Debian"

  - name: install apache and php for CentOS servers
    tags: apache,centos,httpd
    ansible.builtin.dnf:
      name:
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_facts['distribution'] == "CentOS"
  
  - name: copy default html file for site
    tags: apache,apche2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644
- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package (CentOS)
    tags: centos,db,mariadb
    ansible.builtin.dnf:
      name: mariadb
      state: latest
    when: ansible_facts['distribution'] == "CentOS"

  - name: install mariadb package (Ubuntu)
    tags: db,mariadb,ubuntu
    ansible.builtin.apt:
      name: mariadb-server
      state: latest
    when: ansible_facts['os_family'] == "Debian" 
