---

- hosts: all
  become: true
  tasks:
 
  - name: install apache and php packages for Ubuntu servers
    ansible.builtin.apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_facts['os_family'] == "Debian"

  - name: install apache and php for CentOS servers
    ansible.builtin.dnf:
      name:
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_facts['distribution'] == "CentOS"
